execute pathogen#infect()

" show color display
" if not, specify [ syntax off ]
syntax on
filetype plugin indent on

colorscheme darkblue

set tabstop=2

" enable auto indent
" if not, specify [ noautoindent ]
set autoindent
set expandtab
set softtabstop=2
set cursorline

" specify encoding
set encoding=utf-8

" specify file formats
set fileformats=unix,dos

" number of search histories
set history=50

" highlights matched words
" if not, specify [ set nohlsearch ]
set hlsearch

" change colors for comments if it's set [ syntax on ]
highlight Comment ctermfg=LightCyan

" Configuration vim Airline
set laststatus=2

let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1

" Configuration NERDTree
map <F5> :NERDTreeToggle<CR>

" Configuration floaterm
let g:floaterm_keymap_toggle = '<F12>'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.9

" Configuration Vim.FZF
let g:fzf_preview_window = 'right:50%'
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6  }  }
